var allText = {
	"healthQuestion": ["Economically healthy cities tended to be more inclusive than economically distressed cities. This is especially true when it comes to economic inclusion."],
	"sizeQuestion": ["Smaller cities tended to be more inclusive than larger ones."],
	"changeQuestion": ["It depends. But, on average, cities that went through an economic recovery became more inclusive.","Forty-one of the 274 cities in our study moved from economically distressed to economically healthy at some point between 1980 and 2013. During their recovery periods, over half became more inclusive, jumping up an average 20 spots on overall inclusion, while 18 cities lost ground.","On average, improvements were greater than declines. For example, Midland, Texas, had the second-largest increase in overall inclusion during its recovery period, jumping 160 spots. On the other hand, North Las Vegas, which lost the most ground, dropped only 132 spots.","Racial inclusion tended to improve more than economic inclusion during an economic recovery. And small cities that went through a recovery tended to become more inclusive during their recovery than larger cities."],
	"mainHeader": ["Everyone should have the opportunity to contribute to and benefit from economic prosperity. This is our definition of inclusion and is a goal toward which all cities should strive. Being more inclusive can make cities stronger and more stable and gives all residents a chance to improve their quality of life.","To better understand what makes cities inclusive, we collected data on the 274 largest US cities and ranked those cities on three measures of inclusion across four decades. We also measured economic health to see whether cities could harness growth to improve inclusion Use our dashboard to explore national trends, learn lessons from case-study cities, and dig deeper into your own city."],
	"cityHeaderBothChange":["In 2013, <span class = \"ch-cityName\"></span> ranked <span class = \"ch-overallRank13\"></span> out of 274 cities on overall inclusion, <span class = \"ch-econRank13\"></span> in economic inclusion, and <span class = \"ch-racialRank13\"></span> in racial inclusion. From 2000 to 2013, <span class = \"ch-cityName\"></span>&rsquo;s economic health rank <span class = \"ch-healthWord\"></span> from <span class = \"ch-healthRank00\"></span> to <span class = \"ch-healthRank13\"></span>. The city also became <span class = \"ch-overallWord\"></span> inclusive, <span class = \"ch-overallWord2\"></span> from <span class = \"ch-overallRank00\"></span> to <span class = \"ch-overallRank13\"></span> in the overall inclusion rankings. Dive deeper into <span class = \"ch-cityName\"></span>&rsquo;s economic health and inclusion measures below."],
	"cityHeaderNoHealthChange":["In 2013, <span class = \"ch-cityName\"></span> ranked <span class = \"ch-overallRank13\"></span> out of 274 cities on overall inclusion, <span class = \"ch-econRank13\"></span> in economic inclusion, and <span class = \"ch-racialRank13\"></span> in racial inclusion. From 2000 to 2013, <span class = \"ch-cityName\"></span>&rsquo;s economic health rank stayed the same at <span class = \"ch-healthRank13\"></span> out of 274 cities. The city also became <span class = \"ch-overallWord\"></span> inclusive, <span class = \"ch-overallWord2\"></span> from <span class = \"ch-overallRank00\"></span> to <span class = \"ch-overallRank13\"></span> in the overall inclusion rankings. Dive deeper into <span class = \"ch-cityName\"></span>&rsquo;s economic health and inclusion measures below."],
	"cityHeaderNoOverallChange":["In 2013, <span class = \"ch-cityName\"></span> ranked <span class = \"ch-overallRank13\"></span> out of 274 cities on overall inclusion, <span class = \"ch-econRank13\"></span> in economic inclusion, and <span class = \"ch-racialRank13\"></span> in racial inclusion. From 2000 to 2013, <span class = \"ch-cityName\"></span>&rsquo;s economic health rank <span class = \"ch-healthWord\"></span> from <span class = \"ch-healthRank00\"></span> to <span class = \"ch-healthRank13\"></span>. The city’s overall inclusion rank—<span class = \"ch-overallRank13\"></span> of 274—did not change. Dive deeper into <span class = \"ch-cityName\"></span>&rsquo;s economic health and inclusion measures below."],
	"consolidatedNote": ["<strong>Note:</strong> <span class = \"note-cityName\"></span> became a consolidated city in <span class = \"note-year\"></span>, so improvements in inclusion may reflect changing boundaries rather than actual gains for city residents. We tracked city boundaries as they changed over the period of our analysis (1980&ndash;2013 for our inclusion measures and 1970&ndash;2013 for economic health measures)."]
}